// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"
)

type Querier interface {
	AddCartItem(ctx context.Context, arg AddCartItemParams) (*CartItem, error)
	CreateCart(ctx context.Context, arg CreateCartParams) (*Cart, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (*Category, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (*Order, error)
	CreateStock(ctx context.Context, arg CreateStockParams) (*Stock, error)
	CreateStockMovement(ctx context.Context, arg CreateStockMovementParams) (*CreateStockMovementRow, error)
	DeleteCategory(ctx context.Context, id uint32) error
	GetCart(ctx context.Context, id uint32) (*Cart, error)
	GetCategory(ctx context.Context, id uint32) (*Category, error)
	GetOrder(ctx context.Context, id uint32) (*Order, error)
	GetStock(ctx context.Context, id uint32) (*Stock, error)
	ListCategories(ctx context.Context, arg ListCategoriesParams) ([]*Category, error)
	ListOrders(ctx context.Context, arg ListOrdersParams) ([]*Order, error)
	ListStocks(ctx context.Context, arg ListStocksParams) ([]*Stock, error)
	RemoveCartItem(ctx context.Context, arg RemoveCartItemParams) error
	UpdateCartItemQuantity(ctx context.Context, arg UpdateCartItemQuantityParams) error
	UpdateCartStatus(ctx context.Context, arg UpdateCartStatusParams) (*Cart, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (*Category, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (*Order, error)
	UpdateStock(ctx context.Context, arg UpdateStockParams) (*Stock, error)
}

var _ Querier = (*Queries)(nil)
