// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"
)

type Querier interface {
	AddCartItem(ctx context.Context, arg AddCartItemParams) error
	AddOrderItems(ctx context.Context, arg []AddOrderItemsParams) *AddOrderItemsBatchResults
	AdjustStock(ctx context.Context, arg []AdjustStockParams) *AdjustStockBatchResults
	AssignProductToCategory(ctx context.Context, arg AssignProductToCategoryParams) error
	ClearCartItems(ctx context.Context, cartID uint64) error
	CreateCart(ctx context.Context, arg CreateCartParams) error
	CreateCategory(ctx context.Context, arg CreateCategoryParams) error
	CreateEvent(ctx context.Context, arg CreateEventParams) error
	CreateOrder(ctx context.Context, arg CreateOrderParams) (*CreateOrderRow, error)
	CreateStockMovement(ctx context.Context, arg []CreateStockMovementParams) *CreateStockMovementBatchResults
	DeleteCategory(ctx context.Context, id int32) error
	DeleteOrder(ctx context.Context, id int32) error
	DeleteOrderItem(ctx context.Context, id int32) error
	FindActiveCartByCustomerID(ctx context.Context, customerID string) (*FindActiveCartByCustomerIDRow, error)
	FindCartItemByProductID(ctx context.Context, arg FindCartItemByProductIDParams) (*CartItem, error)
	GetCart(ctx context.Context, id int32) (*GetCartRow, error)
	GetCartItem(ctx context.Context, id int32) (*CartItem, error)
	GetCategoryByID(ctx context.Context, id int32) (*Category, error)
	GetEventByID(ctx context.Context, id string) (*Event, error)
	GetOrder(ctx context.Context, id int32) (*GetOrderRow, error)
	GetOrderByCustomerIDAndSubscriptionID(ctx context.Context, arg GetOrderByCustomerIDAndSubscriptionIDParams) (*GetOrderByCustomerIDAndSubscriptionIDRow, error)
	GetOrderByInvoiceID(ctx context.Context, invoiceID *string) (*GetOrderByInvoiceIDRow, error)
	GetOrderByPaymentIntentID(ctx context.Context, paymentIntentID *string) (*GetOrderByPaymentIntentIDRow, error)
	GetOrderByRefundID(ctx context.Context, refundID *string) (*GetOrderByRefundIDRow, error)
	GetOrderItem(ctx context.Context, id int32) (*GetOrderItemRow, error)
	GetStock(ctx context.Context, id int32) (*Stock, error)
	GetStockMovementsByReference(ctx context.Context, arg GetStockMovementsByReferenceParams) ([]*StockMovement, error)
	ListCartItems(ctx context.Context, cartID uint64) ([]*CartItem, error)
	ListCategories(ctx context.Context, arg ListCategoriesParams) ([]*Category, error)
	ListOrderItems(ctx context.Context, orderID int32) ([]*ListOrderItemsRow, error)
	ListOrders(ctx context.Context, arg ListOrdersParams) ([]*ListOrdersRow, error)
	ListOrdersByStatus(ctx context.Context, arg ListOrdersByStatusParams) ([]*ListOrdersByStatusRow, error)
	ListStockMovements(ctx context.Context, arg ListStockMovementsParams) ([]*StockMovement, error)
	ListSubcategories(ctx context.Context, parentID *int32) ([]*Category, error)
	MarkEventAsProcessed(ctx context.Context, arg MarkEventAsProcessedParams) error
	ReduceStock(ctx context.Context, arg []ReduceStockParams) *ReduceStockBatchResults
	ReleaseStock(ctx context.Context, arg []ReleaseStockParams) *ReleaseStockBatchResults
	RemoveCartItem(ctx context.Context, id int32) error
	RemoveProductFromCategory(ctx context.Context, arg RemoveProductFromCategoryParams) error
	UpdateCartItem(ctx context.Context, arg UpdateCartItemParams) error
	UpdateCartItemQuantity(ctx context.Context, arg UpdateCartItemQuantityParams) error
	UpdateCartStatus(ctx context.Context, arg UpdateCartStatusParams) error
	UpdateCartTotals(ctx context.Context, arg UpdateCartTotalsParams) error
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) error
	UpdateOrderItem(ctx context.Context, arg UpdateOrderItemParams) error
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error
	UpdateOrderTotals(ctx context.Context, arg UpdateOrderTotalsParams) error
}

var _ Querier = (*Queries)(nil)
